## 1. import an read

In [1]:
import sqlite3
import numpy as np
import pandas as pd
import plotly.graph_objects as go

In [2]:
db = sqlite3.connect("../data/checking-logs.sqlite")

## 2. Preprocessing

In [3]:
data = pd.read_sql("""
            SELECT uid, timestamp, numTrials
            FROM checker WHERE
                status = 'ready'
                AND uid LIKE 'user%'
                AND labname = 'project1'
            """,
            db, parse_dates='timestamp')
data.head()

      uid                  timestamp  numTrials
0  user_4 2020-04-17 05:19:02.744528          1
1  user_4 2020-04-17 05:22:45.549397          2
2  user_4 2020-04-17 05:34:24.422370          3
3  user_4 2020-04-17 05:43:27.773992          4
4  user_4 2020-04-17 05:46:32.275104          5

In [4]:
data['timestamp'] = data.timestamp.dt.date
data = data.sort_values(by='timestamp')

In [5]:
g_data = data.groupby(['uid', 'timestamp'], as_index = False).numTrials.max()
g_data.head()
dates = g_data['timestamp'].unique()

In [6]:
pivot = pd.pivot(data = g_data, index = 'uid', columns = 'timestamp', values = 'numTrials')
pivot.head()

timestamp,2020-04-17,2020-04-18,2020-04-19,2020-04-22,2020-04-23,2020-04-24,2020-05-03,2020-05-04,2020-05-05,2020-05-06,2020-05-07,2020-05-08,2020-05-09,2020-05-10,2020-05-11,2020-05-12,2020-05-13,2020-05-14,2020-05-15
uid,,,,,,,,,,,,,,,,,,,
user_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,NaN
user_10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,21.0,59.0,NaN
user_11,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
user_12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
user_13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,30.0,NaN,32.0,NaN

In [7]:
last_value = 0
for j in range (len(pivot)):
    for i in range (len(pivot.iloc[j])):
        value = pivot.iloc[j][i]
        if 0 < value and value < 999:
            last_value = int(value)
        else:
            pivot.iloc[j][i] = last_value
    last_value = 0
pivot.head()

/var/folders/ts/zy03tlpj0hs45ygzg74rq8jc0000gn/T/ipykernel_3306/3202216683.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  value = pivot.iloc[j][i]
/var/folders/ts/zy03tlpj0hs45ygzg74rq8jc0000gn/T/ipykernel_3306/3202216683.py:8: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  pivot.iloc[j][i] = last_value

timestamp,2020-04-17,2020-04-18,2020-04-19,2020-04-22,2020-04-23,2020-04-24,2020-05-03,2020-05-04,2020-05-05,2020-05-06,2020-05-07,2020-05-08,2020-05-09,2020-05-10,2020-05-11,2020-05-12,2020-05-13,2020-05-14,2020-05-15
uid,,,,,,,,,,,,,,,,,,,
user_1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0,11.0
user_10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,21.0,59.0,59.0
user_11,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
user_12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0
user_13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,30.0,30.0,32.0,32.0

In [8]:
data = pivot
data = data.reset_index()
data.head()

timestamp,uid,2020-04-17,2020-04-18,2020-04-19,2020-04-22,2020-04-23,2020-04-24,2020-05-03,2020-05-04,2020-05-05,2020-05-06,2020-05-07,2020-05-08,2020-05-09,2020-05-10,2020-05-11,2020-05-12,2020-05-13,2020-05-14,2020-05-15
0,user_1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0,11.0
1,user_10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,21.0,59.0,59.0
2,user_11,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
3,user_12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0
4,user_13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,30.0,30.0,32.0,32.0

## 3. Creating graph like in reference

In [9]:
num_rows = data.shape[0]
num_cols = data.shape[1]
num_frames = num_cols - 1
xaxis_range = [0,num_frames + 2]
x_init = np.array([1])

In [10]:
initial_data = []
for id in data['uid'].unique():
    y_axis = np.array(id)
    initial_data.append(go.Scatter(x =x_init, y = y_axis,mode = "lines",name = id))
initial_max = 600

In [11]:
frames = []
for f in range (1,num_frames):
    x_axis = np.arange(1,f+1)
    date = str(data.columns[f])
    curr_data = [] 
    title_names = [] 
    start = "For " + date
    for id in data['uid'].unique():
        y_axis = np.array(data[data.uid == id].values.tolist()[0][1:f+1])
        y_axis[0] = 0
        curr_data.append(go.Scatter(x = x_axis, y = y_axis,mode = "lines+markers", name = id))
        title_names.append(id + ": " + str(y_axis[f-1]) +"commit")
    curr_frame = go.Frame(data = curr_data)
    frames.append(curr_frame)

In [12]:
figure = go.Figure(
    data = initial_data,
    layout = {
        "title":"Dynamic of commits per user in project1",
        "xaxis":{"range":xaxis_range, "visible":True, "showline":False},
        "yaxis":{"range": [0, 170], "visible":True, "showline":False},
        "updatemenus":[{"type":"buttons","buttons":[{"method":"animate","label":"play", "args":[None]}]}]
        },
    frames = frames
    )
figure.layout.template='seaborn'

In [13]:
figure.show()

In [14]:
db.close()